name: Build and push Docker image

on:
  workflow_run:
    workflows: [goreleaser]
    types: [completed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/figglewatts/certexpired
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=ref,event=tag
      - name: Extract tag name
        run: |
          echo "GIT_TAG=$(git tag --sort=-creatordate | head -n 1)" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.GIT_TAG }}